# Points at a github repository with a single manifest with one environment, one namespace and one repo
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: git-demo-dev
  namespace: fluxdemo-dev
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/wolcn/flux-dev
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: git-dev
  namespace: fluxdemo-dev
spec:
  interval: 20m0s
  path: ./dev
  prune: true
  serviceAccountName: fluxdemo-dev
  sourceRef:
    kind: GitRepository
    name: git-demo-dev
