---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-dev
  namespace: fluxdemo-dev
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/wolcn/flux-dev
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-dev
  namespace: fluxdemo-dev
spec:
  interval: 30m0s
  path: ./dev
  prune: true
  serviceAccountName: fluxdemo-dev
  sourceRef:
    kind: GitRepository
    name: flux-dev
