# Points to an OCI artifact which is basically the manifest file for the git repo with names
# changed so that the deployments don't mess with each other
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: oci-demo-dev
  namespace: fluxdemo-dev
spec:
  interval: 1m # source polling interval
  url: oci://ghcr.io/wolcn/kcheck/kcheck-dev
  ref:
    tag: latest
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: oci-dev
  namespace: fluxdemo-dev
spec:
  interval: 1h # drift detection interval
  path: ./
  prune: true
  serviceAccountName: fluxdemo-dev
  sourceRef:
    kind: OCIRepository
    name: oci-demo-dev
